### PR TITLE
fix: sendMessage promise should resolve to undefined when no listeners reply

### LINKED ISSUE #130: Chrome: "The message port closed before a response was received."
**Minimal repro repo:**
https://github.com/lydell/webextension-polyfill-messaging-issue

This happens with both v0.2.1 on npm and when built from commit 2537b23837d4752e3a6c3236c2776adbc89f1312.

# Summary

If a `browser.runtime.onMessage` callback does not return a Promise, `browser.runtime.sendMessage` will be rejected with the following error, causing noise in the console:

> "The message port closed before a response was received."

## Workaround

Even if you don't want to send a response, always return a promise
in your `onMessage` callback:

```js
// background.js
browser.runtime.onMessage.addListener(message => {
  console.log("background: onMessage", message);

  // Add this line:
  return Promise.resolve("Dummy response to keep the console quiet");
});
```

You can also make the `onMessage` callback `async` to implicitly return a Promise (resolving to `undefined` in the below example).

```js
// background.js
// Notice the `async` keyword.
browser.runtime.onMessage.addListener(async message => {
  console.log("background: onMessage", message);
});
```

# Files

Copied over for convenience from:
https://github.com/lydell/webextension-polyfill-messaging-issue

```json
{
  "manifest_version": 2,
  "version": "0.0.0",
  "name": "Test",
  "background": {
    "scripts": [
      "browser-polyfill-npm.js",
      "background.js"
    ]
  },
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "browser-polyfill-master.js",
        "content.js"
      ]
    }
  ]
}
```

```js
// background.js

browser.runtime.onMessage.addListener(onMessage);

function onMessage(message) {
  console.log("background: onMessage", message);

  // 1: Causes the following to be logged in content:
  // "The message port closed before a response was received."
  return undefined;

  // 2: Causes this response to be logged in content, as expected.
  // return Promise.resolve("response from background");

  // 3: Causes this error to be logged in content, as expected.
  // return Promise.reject(new Error("Could not respond"));

  // 4: Causes nothing at all to be logged in content!
  // I guess it is waiting for the deprecated `sendResponse` parameter to be
  // called.
  // return true;
}
```

```js
// content.js

// 1: Unless background returns a Promise in its onMessage, this promise is
// rejected with:
// "The message port closed before a response was received."
browser.runtime
  .sendMessage("hello from content")
  .then(console.log, console.error);



// 2: This does not seem to cause any errors:
// chrome.runtime.sendMessage("hello from content");
// console.log("content: after chrome.runtime.sendMessage", chrome.runtime.lastError);



// 3: Inside the callback, `chrome.runtime.lastError` will be:
// "The message port closed before a response was received."
// It seems like if `sendMessage` defines a callback but the other end doesn't
// respond, Chrome is treating that as an error. Which makes sense.
// The question is how this should be handled in a Promise based API.
// chrome.runtime.sendMessage("hello from content", response => {
//   console.log("content: callback", response, chrome.runtime.lastError);
// });
// console.log(
//   "content: after chrome.runtime.sendMessage with callback",
//   chrome.runtime.lastError
// );
```

## Solution?

Should the "The message port closed before a response was received." be detected, and the promise should be resolved with `undefined`?

### PR DESCRIPTION
**Pull request by rpl**
This PR contains the changes from #131 with the addition of some small tweaks (from the last review on #131) and an additional integration test (to check that the behavior of the polyfill in Chrome is the same of the one on Firefox with the native promised APIs).

Fixes #130

### CODE REVIEW

File: test/fixtures/runtime-messaging-extension/content.js [hunk 1]
```diff
@@ -75,3 +75,8 @@ test("sendMessage with listener callback throws", async (t) => {
     t.equal(err.message, "listener throws", "Got an error with the expected message");
   }
 });
+
+test("sendMessage and no listener answers", async (t) => {
+  const reply = await browser.runtime.sendMessage("test - sendMessage and no listener answers");
+  t.equal(reply, undefined, "Got undefined as a reply a expected");
```
Comment (lydell) [inline test/fixtures/runtime-messaging-extension/content.js]: Typo: a<strong>s</strong> expected

File: test/test-runtime-onMessage.js [hunk 2]
```diff
@@ -238,5 +238,30 @@ describe("browser-polyfill", () => {
...
+          // in the polyfill sources and it is used to recognize when Chrome has detected that
+          // none of the listeners replied.
+          lastError: {
+            message: "The message port closed before a response was received.",
+          },
+          sendMessage: sinon.stub(),
+        },
+      };
+
+      fakeChrome.runtime.sendMessage.onFirstCall().callsArgWith(1, ["res1", "res2"]);
```
Comment (Rob--W) [inline test/test-runtime-onMessage.js]: Nit: Use `.callsArg(1)` or `callsArgWith(1, [undefined]);` .
In reality the `sendMessage` callback won't ever be invoked with two arguments.
