### PR TITLE
fix: Throw error when loaded in non-extension contexts

### LINKED ISSUE #186: Inclusion in Firefox throws a console error
Including the polyfill on Firefox throws an error. It does not need to polyfill for Firefox, but I expected its inclusion to not throw an exception.

### The error
```console
ReferenceError: chrome is not defined
```

### The HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://unpkg.com/webextension-polyfill@0.4.0/dist/browser-polyfill.js"></script>
  </head>
  <body>
  </body>
</html>
```

### Screenshot
Screen Shot 2019-05-10 at 16 18 05

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes #186

### CODE REVIEW

File: test/test-proxied-properties.js [hunk 1]
```diff
@@ -159,9 +159,16 @@ describe("browser-polyfill", () => {
...
+          ok(false, "chrome.tabs should not lazily be initialized without explicit API call");
+        },
       };
       return setupTestDOMWindow(fakeChrome).then(window => {
-        equal(lazyInitCount, 0, "chrome.runtime should not be initialized without explicit API call");
+        // This used to be equal(lazyInitCount, 0, ...), but was changed to
+        // accomodate a change in the implementation of the polyfill.
+        // To verify that APIs are not unnecessarily initialized, the fakeChrome
+        // object has a "tabs" getter that fails the test upon access.
+        equal(lazyInitCount, 1, "chrome.runtime should be initialized because chrome.runtime.id is accessed during polyfill intiialization");
```
Comment (rpl) [inline test/test-proxied-properties.js]: Nit, typo: intiialization -> initialization
