### PR TITLE
fix: browser.devtools.inspectedWindow.eval promise should always resolve to an array

### LINKED ISSUE #168: browser.devtools.inspectedWindow.eval() resolves with incorrect promise signature
When calling `browser.devtools.inspectedWindow.eval()` in Chrome (I'm using 71), the resulting promise appears to resolve with an incorrect signature. According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow/eval#Return_value), the resulting promise should be an array containing two elements:

> A Promise that will be fulfilled with an array containing two elements.
>
>If no error occurred, element 0 will contain the result of evaluating the expression, and element 1 will be undefined.
>
>If an error occurred, element 0 will be undefined, and element 1 will contain an object giving details about the error. Two different sorts of errors are distinguished

However, running the following script

```js
let statement = `Array.from(document.querySelectorAll('*')).map(e=>e.tagName)`;
browser.devtools.inspectedWindow.eval(statement).then(console.log);
```

Returns

```js
["HTML", "HEAD", "META", ...]
```

I was expecting

```js
[
  ["HTML", "HEAD", "META", ...],
  undefined
]
```

If I call the same function with a statement that will throw an error, the promise resolves with the correct error signature:

```js
let statement = `%%%`;
browser.devtools.inspectedWindow.eval(statement).then(console.log);
```

Returns:

```js
[
  undefined,
  {
    isException: true,
    value: "SyntaxError: Unexpected token %"
  }
]
```

Firefox behaves as expected.

### PR DESCRIPTION
**Pull request by rpl**
This PR includes the changes needed to ensure that browser.devtools.inspectedWindow.eval returned promise is always resolved to an array (fix #168), and a new integration test to verify it as part of the automated tests.

### CODE REVIEW

File: src/browser-polyfill.js [hunk 1]
```diff
@@ -93,7 +93,13 @@ if (typeof browser === "undefined" || Object.getPrototypeOf(browser) !== Object.
         if (extensionAPIs.runtime.lastError) {
           promise.reject(extensionAPIs.runtime.lastError);
         } else if (metadata.singleCallbackArg || callbackArgs.length <= 1) {
-          promise.resolve(callbackArgs[0]);
+          if (metadata.singleCallbackArg === false) {
+            // Pass the callback arguments as an array even if its length is <= 1
+            // when explicitly requested by the api metadata.
```
Comment (Rob--W) [inline src/browser-polyfill.js]: Collapse clause in parent `if`-condition: `callbackArgs.length <= 1 && metadata.singleCallbackArg !== false`

File: test/fixtures/devtools-extension/devtools_page.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+console.log("devtools page loaded");
+
+browser.runtime.onMessage.addListener(async msg => {
+  switch (msg.apiMethod) {
+    case "devtools.inspectedWindow.eval": {
+      const evalResult = await browser.devtools.inspectedWindow.eval(...msg.params);
+      return Promise.resolve({evalResult});
```
Comment (Rob--W) [inline test/fixtures/devtools-extension/devtools_page.js]: `return {evalResult};` should be sufficient, as you already have `async` above.

File: test/fixtures/devtools-extension/devtools_page.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+    }
+  }
+
+  return Promise.reject(`devtools_page received an unxpected message: ${msg}`);
```
Comment (Rob--W) [inline test/fixtures/devtools-extension/devtools_page.js]: `throw new Error(...);` because the function is already `async`.
