### PR TITLE
fix: wrap `onRequestFinished` to use promises

### LINKED ISSUE #249: `browser.devtools.network.onRequestFinished` does not promisify `getContent()`
On Chrome, `chrome.devtools.network.onRequestFinished.addListener` emits a `chrome.devtools.network.Request` object, which includes a `getContent()` method that invokes a callback with string content and its encoding. Correct usage looks like:

```javascript
chrome.devtools.network.onRequestFinished.addListener((req) => {
  req.getContent((content, encoding) => {
    // ...
  });
});
```

With Web Extensions, `getContent()` should return a `Promise` rather than being callback based. For example:

```javascript
browser.devtools.network.onRequestFinished.addListener(async (req) => {
  const [content, encoding] = await req.getContent();
});
```

Currently however, the Web Extensions polyfill simply passes through what it receives from Chrome, so `getContent()` is still callback based.

I wasn't able to find `browser.devtools` in [the spec](https://browserext.github.io/browserext/), however [MDN does say that this method exists and does in fact return a `Promise`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network/onRequestFinished#Parameters:~:text=arguments%3A-,request). `firefox-webext-browser` also [says this returns `Promise<object>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/acd551e6200f3c55dee83990e5a3419a2e0b7e56/types/firefox-webext-browser/index.d.ts#L5892). I'm not totally clear if this is an official part of the spec, or a Firefox-specific API.

My questions here are:
1. Is `browser.devtools.network.onRequestFinished` actually defined in the Web Extensions spec somewhere?
1. What exactly is the return type? `Promise<object>` is pretty vague and MDN doesn't provide specifics.
    * Chrome returns a tuple of `[string, string]`, where the former is the content as a string or a base64 encoded string (if binary), and the latter is an empty string or `'base64'` (if binary). I'm not sure what the expected behavior of Web Extensions would be for binary data?

I'm happy to write up a PR to implement this if it is appropriate to add to this polyfill. I'm not totally clear on where this API stands with respect to the spec, but if you're willing to merge it, I'm happy to write it.

### PR DESCRIPTION
**Pull request by dgp1130**
Fixes #249.

This updates `browser.devtools.network.onRequestFinished` to emit an
object with a promisified `getContent()` property. This brings the
polyfill implementation in line with Firefox's implementation, although
documentation is still inaccurate at the moment.

Also updates some out of date documentation with `makeCallback()`.

I tested this in my own Chrome extension and it appears to work as expected.

### CODE REVIEW

**Comment by dgp1130** [comment]
CI seems to be having a versioning error with Chrome that seems to be unrelated to this PR?

File: test/test-onRequestFinished.js [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+        wrappedListener({
+          getContent(cb) {
+            cb("<html>...</html>", "text/html; charset=utf8");
+          },
+        });
+
+        ok(listener.calledOnce, "listener has not been called");
+
+        const req = listener.firstCall.args[0];
+        return req.getContent().then(([content, encodingOrMimeType]) => {
```
Comment (Rob--W) [inline test/test-onRequestFinished.js:69]: You should add a test to verify that the `getContent` method still accepts a callback.

**Review by Rob--W — CHANGES_REQUESTED** [review]

**Comment by Rob--W** [comment]
> CI seems to be having a versioning error with Chrome that seems to be unrelated to this PR?

I'll take care of that in #251

File: src/browser-polyfill.js [hunk 2]
```diff
@@ -345,6 +349,32 @@ if (typeof browser === "undefined" || Object.getPrototypeOf(browser) !== Object.
...
+       * Wraps an onRequestFinished listener function so that it will return a
+       * `getContent()` property which returns a `Promise` rather than using a
+       * callback API.
+       *
+       * @param {object} req
+       *        The HAR entry object representing the network request.
+       */
+      return function onRequestFinished(req) {
+        listener({
+          ...req,
```
[the remark this answers is not in the document]
Comment (dgp1130) [reply src/browser-polyfill.js]: Good catch, updated to use `wrapObject()`, which I think is what you meant by your example. Also added a test which extends a prototype to confirm the behavior. Let me know if I'm misunderstanding how this should be implemented.

File: src/browser-polyfill.js [hunk 3]
```diff
@@ -77,13 +77,17 @@ if (typeof browser === "undefined" || Object.getPrototypeOf(browser) !== Object.
...
      *        The promise's resolution function.
-     * @param {function} promise.rejection
+     * @param {function} promise.reject
      *        The promise's rejection function.
      * @param {object} metadata
      *        Metadata about the wrapped method which has created the callback.
-     * @param {integer} metadata.maxResolvedArgs
-     *        The maximum number of arguments which may be passed to the
-     *        callback created by the wrapped async function.
+     * @param {boolean} metadata.singleCallbackArg
```
[the remark this answers is not in the document]
Comment (dgp1130) [reply src/browser-polyfill.js:84]: Done. `metadata.fallbackToNoCallback` and `metadata.noCallback` are still not documented for `wrapAsyncFunction()`, but I don't fully understand the subtleties of their usage, so I left them out for now.

File: test/test-onRequestFinished.js (hunk 1 above)
Comment (dgp1130) [reply test/test-onRequestFinished.js:69]: Are you suggesting that `wrappedReq.getContent(([content, encodingOrMimeType]) => { /* ... */})` should still work? Adding a test for this fails and I believe that is the way `wrapAsyncFunction()` works so I don't think we would expect callback usage to work. I also think that isn't the way Firefox does this I would think supporting that isn't necessarily expected behavior for this polyfill.

Am I misunderstanding something or are there additional changes to be made to support a callback API on top of the `Promise` API?

Comment (Rob--W) [reply test/test-onRequestFinished.js:69]: Oops, never mind. We do intentionally not support callbacks in the API, per https://github.com/mozilla/webextension-polyfill#no-callback-supported-by-the-promise-based-apis-on-chrome

File: test/test-onRequestFinished.js [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+
+        const requestProto = {
+          inheritedProp() {},
+        };
+        const request = {
+          getContent(cb) {
+            cb("<html>...</html>", "text/html; charset=utf8");
+          },
+        };
+        Object.setPrototypeOf(request, requestProto);
```
Comment (Rob--W) [inline test/test-onRequestFinished.js:110]: Simplify to
```javascript
const request = Object.create({
  inheritedProp: true,
  getContent(cb) {
    cb("", "");
  },
});
```

File: test/test-onRequestFinished.js [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+           "devtools.network.onRequestFinished.addListener should have been called once");
+
+        const wrappedListener = fakeChromeOnRequestFinished.addListener.firstCall.args[0];
+        wrappedListener({
+          getContent(cb) {
+            cb("<html>...</html>", "text/html; charset=utf8");
+          },
+        });
+
+        ok(listener.calledOnce, "listener has not been called");
```
Comment (Rob--W) [inline test/test-onRequestFinished.js:66]: This and some other messages: make sure that the message describes the expected behavior.

`onRequestFinished has been called once` is a better description.

**Review by Rob--W — CHANGES_REQUESTED** [review]

File: test/test-onRequestFinished.js (hunk 4 above)
Comment (dgp1130) [reply test/test-onRequestFinished.js]: Done.

File: test/test-onRequestFinished.js (hunk 5 above)
Comment (dgp1130) [reply test/test-onRequestFinished.js]: Done.

**Review by Rob--W — APPROVED** [review]
LGTM thanks. I'll merge it after the other PR that unbreaks the build is merged.

**Comment by Rob--W** [comment]
The other PR got approved and merged. Could you rebase and update the PR so we can get a green CI build?

**Comment by dgp1130** [comment]
Rebased and got a green CI, thanks for fixing that.

**Comment by Rob--W** [comment]
Thanks for the report and patch!

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @dgp1130! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Take care!
